apiVersion: v1
kind: Service
metadata:
  namespace: no-db-rails
  name: scaling-out-no-db-rails
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: no-db-rails
